name: Update Website Content

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Configure JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run checks
        run: ./gradlew check

      - name: Update website content
        run: ./gradlew :datasync:runUpdateData

      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Auto update website content

